### ISSUE TITLE
Kubernetes cluster credentials management

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/tng-sp-ia-k8s#4]
**Objectives:**
We need to have the configuration of the kubernetes clusters stored, providing security of the data

**Requirements:**
- Configuration Manager: read, write, delete, update the credentials.
- The credentials have to be stored encrypted

**TODO:**
- [x]  Evaluate databases solution for storing k8s credentials (Postgres / Mongo)
- [x]  Classes to handle Read/Write?/Delete?/Update?
- [x]  Integration tests wrapper <-> Database
- [x] Documentation
